version: "3.4"

networks:
    n-hashbrown: ~
    
services:
    node:
        image: node
        container_name: "hashbrown-node"
        ports:
            - "8080:8080"
        depends_on:
            - mongodb
        networks:
            - n-hashbrown
        restart: unless-stopped
        command: "node /opt/hashbrown-cms"
        environment:
            - MONGODB_HOST=mongodb
        volumes:
            - "./:/opt/hashbrown-cms"
            - "./remote:/remote"

    mongodb:
        image: mongo
        container_name: "hashbrown-mongo"
        networks:
            - n-hashbrown
        restart: unless-stopped
        volumes:
            - "./db:/data/db"
